# Generated by Django 3.2.5 on 2021-12-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('rid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=10000)),
                ('hours', models.JSONField()),
            ],
            options={
                'db_table': 'restaurants',
            },
        ),
    ]
